service: fastapi-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource:
            - arn:aws:ssm:ap-southeast-1:699475917025:parameter/pagbantay-be/database/url

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: public.ecr.aws/sam/build-python3.11
    useStaticCache: false
    zip: true
    preRequirementsCommand: "./.serverless/apt-get-install.sh"

package:
  exclude:
    - .git/**
    - .github/**
    - tests/**
    - README.md
    - docs/**
    - .gitignore
    - .vscode/**
    - .env
    - node_modules/**
    - cockroach-v23.1.11.linux-amd64/**
    - _pycache_/**
    - .serverless/**
    - .venv/**
    - local-data/**
    - repositories/**
