"""Removed station assignment in Availability Table

Revision ID: 0edaf2a4e264
Revises: 242250149749
Create Date: 2025-05-28 15:56:08.907765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edaf2a4e264'
down_revision = '242250149749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Availability', 'station_assignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Availability', sa.Column('station_assignment', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
