"""Fixed typo causing mismatch in User - VolunteerAssignment relationship

Revision ID: 1214a2ecb556
Revises: 33b21569de20
Create Date: 2025-05-06 01:13:15.077719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1214a2ecb556'
down_revision = '33b21569de20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
