"""Added Availabilities Table

Revision ID: 210bf9866765
Revises: 9df9e0e75ede
Create Date: 2025-05-01 00:49:59.993917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210bf9866765'
down_revision = '9df9e0e75ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Availability',
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('station_assignment', sa.String(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('availability_id')
    )
    op.create_foreign_key(None, 'Volunteer Assignment', 'Event', ['event_id'], ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Volunteer Assignment', type_='foreignkey')
    op.drop_table('Availability')
    # ### end Alembic commands ###
