"""Added Cascade on delete for Foreign Keys related to Events Table

Revision ID: 242250149749
Revises: 338ba192fd60
Create Date: 2025-05-15 01:15:35.761672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242250149749'
down_revision = '338ba192fd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Availability_event_id_fkey', 'Availability', type_='foreignkey')
    op.create_foreign_key(None, 'Availability', 'Event', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.drop_constraint('Volunteer Assignment_event_id_fkey', 'Volunteer Assignment', type_='foreignkey')
    op.create_foreign_key(None, 'Volunteer Assignment', 'Event', ['event_id'], ['event_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Volunteer Assignment', type_='foreignkey')
    op.create_foreign_key('Volunteer Assignment_event_id_fkey', 'Volunteer Assignment', 'Event', ['event_id'], ['event_id'])
    op.drop_constraint(None, 'Availability', type_='foreignkey')
    op.create_foreign_key('Availability_event_id_fkey', 'Availability', 'Event', ['event_id'], ['event_id'])
    # ### end Alembic commands ###
