"""Renamed start-time and end-time columns

Revision ID: 338ba192fd60
Revises: 9d606c2c544f
Create Date: 2025-05-14 20:27:44.275384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338ba192fd60'
down_revision = '9d606c2c544f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('Event', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.drop_column('Event', 'shift_end_time')
    op.drop_column('Event', 'shift_start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('shift_start_time', sa.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Event', sa.Column('shift_end_time', sa.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Event', 'end_time')
    op.drop_column('Event', 'start_time')
    # ### end Alembic commands ###
