"""Updated relationship between User and Volunteer Assignment tables

Revision ID: 33b21569de20
Revises: 58b235c9ab85
Create Date: 2025-05-06 01:09:51.723896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b21569de20'
down_revision = '58b235c9ab85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
