"""Replaced all IDs with type String from type Integer

Revision ID: 7ef2fa207141
Revises: ba5e8d0709da
Create Date: 2025-05-01 22:44:15.564392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef2fa207141'
down_revision = 'ba5e8d0709da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
