"""empty message

Revision ID: 8088eeb7961d
Revises: b94dc48d19d7
Create Date: 2025-04-25 15:45:43.169609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8088eeb7961d'
down_revision = 'b94dc48d19d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
