"""Added unique UUID generation for all primary keys

Revision ID: 8428d036df91
Revises: 7ef2fa207141
Create Date: 2025-05-01 23:01:47.976155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8428d036df91'
down_revision = '7ef2fa207141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
