"""Added start-time and end-time in Events Table, also removed unnecessary columns

Revision ID: 9d606c2c544f
Revises: c09f2cd3b2de
Create Date: 2025-05-14 20:17:06.662698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d606c2c544f'
down_revision = 'c09f2cd3b2de'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('DELETE FROM "Availability"')
    op.execute('DELETE FROM "Volunteer Assignment"')
    op.execute('DELETE FROM "Event"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('shift_start_time', sa.DateTime(), nullable=False))
    op.add_column('Event', sa.Column('shift_end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Event', 'shift_end_time')
    op.drop_column('Event', 'shift_start_time')
    op.add_column('Availability', sa.Column('station_assignment', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
