"""Removed Stations table and adjusted other attributes accordingly

Revision ID: 9df9e0e75ede
Revises: 8e7e36c09446
Create Date: 2025-04-30 23:47:49.780421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df9e0e75ede'
down_revision = '8e7e36c09446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Volunteer Assignment_station_id_fkey', 'Volunteer Assignment', type_='foreignkey')
    op.drop_table('Station')
    op.add_column('Volunteer Assignment', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('Volunteer Assignment', sa.Column('station', sa.String(), nullable=False))
    op.drop_column('Volunteer Assignment', 'station_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Volunteer Assignment', sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Volunteer Assignment', type_='foreignkey')
    op.create_foreign_key('Volunteer Assignment_station_id_fkey', 'Volunteer Assignment', 'Station', ['station_id'], ['station_id'])
    op.drop_column('Volunteer Assignment', 'station')
    op.drop_column('Volunteer Assignment', 'event_id')
    op.create_table('Station',
    sa.Column('station_id', sa.INTEGER(), server_default=sa.text('unique_rowid()'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_people_needed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], name='Station_event_id_fkey'),
    sa.PrimaryKeyConstraint('station_id', name='Station_pkey'),
    comment='Identifies the maximum selected value.'
    )
    # ### end Alembic commands ###
