"""Removed Notifications Table

Revision ID: a020f07c3227
Revises: 210bf9866765
Create Date: 2025-05-01 00:52:28.948603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a020f07c3227'
down_revision = '210bf9866765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notification',
    sa.Column('notification_id', sa.INTEGER(), server_default=sa.text('unique_rowid()'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='Notification_user_id_fkey'),
    sa.PrimaryKeyConstraint('notification_id', name='Notification_pkey'),
    comment='Calculates the boolean value of `AND`ing all selected values.'
    )
    # ### end Alembic commands ###
