"""Add tables according to schema in models/base.py

Revision ID: b94dc48d19d7
Revises: 
Create Date: 2025-04-07 00:11:39.883773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94dc48d19d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Admin Access',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('Notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('Event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['Admin Access.admin_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('Station',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('number_of_people_needed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('Volunteer Assignment',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('shift_start_time', sa.DateTime(), nullable=False),
    sa.Column('shift_end_time', sa.DateTime(), nullable=False),
    sa.Column('availability_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['Station.station_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Volunteer Assignment')
    op.drop_table('Station')
    op.drop_table('Event')
    op.drop_table('Notification')
    op.drop_table('Admin Access')
    op.drop_table('User')
    # ### end Alembic commands ###
