"""Fixed relationship mapping between Even and AdminAccess models

Revision ID: ba5e8d0709da
Revises: fd8b504e0eef
Create Date: 2025-05-01 01:38:02.946991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5e8d0709da'
down_revision = 'fd8b504e0eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
