"""Removed self pointing relationship of Events Table in base schema

Revision ID: fd8b504e0eef
Revises: a020f07c3227
Create Date: 2025-05-01 01:27:23.182345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8b504e0eef'
down_revision = 'a020f07c3227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
